package com.remoteagent.mobile;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.view.*; import android.view.inputmethod.InputMethodManager; import android.widget.*; import org.json.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.text.*; import java.util.*;

/** A small, dependency-free OpenAI-compatible mobile client. Credentials remain on this device. */
public class MainActivity extends Activity {
    private LinearLayout feed, tasks; private EditText composer; private TextView status; private SharedPreferences prefs; private final Handler ui = new Handler(Looper.getMainLooper());
    private final ArrayList<Message> messages = new ArrayList<>(); private final ArrayList<Task> taskList = new ArrayList<>();
    private int blue=Color.rgb(20,108,148);
    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("agent",MODE_PRIVATE); load(); showChat();}
    private TextView label(String s,int size){ TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setPadding(24,16,24,16);return v; }
    private Button button(String s){Button b=new Button(this);b.setText(s);return b;}
    private LinearLayout root(){ LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.WHITE);return r; }
    private void header(LinearLayout r,String title){ LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setBackgroundColor(blue); TextView t=label(title,20);t.setTextColor(Color.WHITE); h.addView(t,new LinearLayout.LayoutParams(0,-2,1)); Button history=button("浠诲姟");history.setOnClickListener(v->showTasks());h.addView(history);Button settings=button("璁剧疆");settings.setOnClickListener(v->showSettings());h.addView(settings);r.addView(h); }
    private void showChat(){ LinearLayout r=root();header(r,"Remote Agent"); status=label(isConfigured()?"宸插氨缁?路 " + prefs.getString("model","gpt-5-mini"):"璇峰厛瀹屾垚杩炴帴璁剧疆",13);status.setTextColor(Color.DKGRAY);r.addView(status);
        ScrollView sc=new ScrollView(this); feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);sc.addView(feed);r.addView(sc,new LinearLayout.LayoutParams(-1,0,1));renderMessages();
        LinearLayout bar=new LinearLayout(this);bar.setPadding(12,8,12,8);composer=new EditText(this);composer.setHint("缁?Agent 涓嬭揪浠诲姟鎴栧彂閫佹秷鎭€?);composer.setMinLines(1);composer.setMaxLines(4);bar.addView(composer,new LinearLayout.LayoutParams(0,-2,1));Button send=button("鍙戦€?);send.setOnClickListener(v->send());bar.addView(send);r.addView(bar);setContentView(r); }
    private void renderMessages(){if(feed==null)return;feed.removeAllViews();for(Message m:messages){TextView v=label((m.user?"浣燶n":"Agent\n")+m.text,16);v.setTextColor(m.user?Color.rgb(12,75,110):Color.DKGRAY);v.setBackgroundColor(m.user?Color.rgb(232,245,252):Color.rgb(246,246,246));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(16,8,16,8);feed.addView(v,p);}}
    private void send(){String text=composer.getText().toString().trim();if(text.isEmpty())return;if(!isConfigured()){showSettings();Toast.makeText(this,"璇烽厤缃湇鍔″湴鍧€鍜?API Key",Toast.LENGTH_LONG).show();return;} Message m=new Message(true,text);messages.add(m);Task t=new Task(text,"杩涜涓?);taskList.add(0,t);save();composer.setText("");renderMessages();status.setText("Agent 姝ｅ湪澶勭悊鈥?);new Thread(()->callAgent(text,t)).start();}
    private void callAgent(String text,Task task){try{String answer=new ApiClient(prefs).ask(text,conversation()); task.status="宸插畬鎴?;messages.add(new Message(false,answer));}catch(Exception e){task.status="澶辫触";messages.add(new Message(false,"璇锋眰澶辫触锛?+e.getMessage()));}save();ui.post(()->{renderMessages();status.setText("宸插氨缁?);});}
    private JSONArray conversation() throws JSONException {JSONArray a=new JSONArray();for(Message m:messages){JSONObject x=new JSONObject();x.put("role",m.user?"user":"assistant");x.put("content",m.text);a.put(x);}return a;}
    private boolean isConfigured(){return !prefs.getString("base","https://api.openai.com/v1").trim().isEmpty()&&!prefs.getString("key","").trim().isEmpty();}
    private void showTasks(){ LinearLayout r=root();header(r,"浠诲姟鍘嗗彶");tasks=new LinearLayout(this);tasks.setOrientation(LinearLayout.VERTICAL);ScrollView s=new ScrollView(this);s.addView(tasks);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));for(Task t:taskList){TextView v=label(t.status+"\n"+t.title+"\n"+t.time,16);v.setPadding(24,22,24,22);tasks.addView(v);}Button back=button("杩斿洖鑱婂ぉ");back.setOnClickListener(v->showChat());r.addView(back);setContentView(r);}
    private void showSettings(){ LinearLayout r=root();header(r,"杩炴帴璁剧疆"); TextView note=label("鎺ㄨ崘锛氱敓浜т娇鐢ㄦ椂灏?API Key 鏀惧湪浣犺嚜宸辩殑鏈嶅姟绔綉鍏炽€傜洿鎺ヤ繚瀛樺湪鎵嬫満涓婄殑 Key 浠呴€傚悎涓汉鍘熷瀷锛涙墍鏈夐€氫俊浠嶅繀椤婚€氳繃 HTTPS銆?,14);note.setTextColor(Color.DKGRAY);r.addView(note);
        EditText base=field("鏈嶅姟绔湴鍧€锛圤penAI: https://api.openai.com/v1锛?,prefs.getString("base","https://api.openai.com/v1"));EditText key=field("API Key锛堜粎淇濆瓨鍦ㄦ湰鏈猴級",prefs.getString("key",""));key.setInputType(129);EditText model=field("妯″瀷",prefs.getString("model","gpt-5-mini"));EditText proxy=field("HTTP 浠ｇ悊锛堝彲閫夛紝濡?host:port锛?,prefs.getString("proxy",""));r.addView(base);r.addView(key);r.addView(model);r.addView(proxy);Button save=button("淇濆瓨骞惰繑鍥?);save.setOnClickListener(v->{String endpoint=base.getText().toString().trim();if(!endpoint.startsWith("https://")){Toast.makeText(this,"鏈嶅姟绔湴鍧€蹇呴』浣跨敤 HTTPS",Toast.LENGTH_LONG).show();return;}prefs.edit().putString("base",endpoint).putString("key",key.getText().toString().trim()).putString("model",model.getText().toString().trim()).putString("proxy",proxy.getText().toString().trim()).apply();showChat();});r.addView(save);TextView help=label("鍏煎鏂瑰紡锛氶粯璁ゅ悜 /responses 鍙戣捣 OpenAI Responses API 璇锋眰锛涜嫢浣犵殑鑷缓 Agent 鏈嶅姟浣跨敤鍏朵粬鍗忚锛岃鍦ㄥ叾缃戝叧涓浆鎹㈣璇锋眰銆備唬鐞嗛厤缃彧鐢ㄤ簬鍚堟硶缃戠粶璺敱锛屼笉鍖呭惈 VPN 鎴栦换浣曠粫杩囬檺鍒跺姛鑳姐€?,13);r.addView(help);setContentView(r);}
    private EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setPadding(24,16,24,16);return e;}
    private void save(){try{JSONArray ma=new JSONArray(),ta=new JSONArray();for(Message m:messages)ma.put(m.json());for(Task t:taskList)ta.put(t.json());prefs.edit().putString("messages",ma.toString()).putString("tasks",ta.toString()).apply();}catch(Exception ignored){}}
    private void load(){try{JSONArray a=new JSONArray(prefs.getString("messages","[]"));for(int i=0;i<a.length();i++)messages.add(Message.from(a.getJSONObject(i)));JSONArray t=new JSONArray(prefs.getString("tasks","[]"));for(int i=0;i<t.length();i++)taskList.add(Task.from(t.getJSONObject(i)));}catch(Exception ignored){}}
    static class Message {boolean user;String text;Message(boolean u,String s){user=u;text=s;}JSONObject json()throws JSONException{return new JSONObject().put("user",user).put("text",text);}static Message from(JSONObject o)throws JSONException{return new Message(o.getBoolean("user"),o.getString("text"));}}
    static class Task {String title,status,time;Task(String x,String s){title=x;status=s;time=DateFormat.getDateTimeInstance().format(new Date());}JSONObject json()throws JSONException{return new JSONObject().put("title",title).put("status",status).put("time",time);}static Task from(JSONObject o)throws JSONException{Task t=new Task(o.getString("title"),o.getString("status"));t.time=o.getString("time");return t;}}
    static class ApiClient {SharedPreferences p;ApiClient(SharedPreferences x){p=x;}String ask(String text,JSONArray history)throws Exception{String base=p.getString("base","").replaceAll("/+$","");URL url=new URL(base+"/responses");String proxy=p.getString("proxy","").trim();HttpURLConnection c;if(proxy.isEmpty())c=(HttpURLConnection)url.openConnection();else{String[] bits=proxy.replace("http://","").split(":");if(bits.length!=2)throw new Exception("浠ｇ悊鏍煎紡搴斾负 host:port");c=(HttpURLConnection)url.openConnection(new Proxy(Proxy.Type.HTTP,new InetSocketAddress(bits[0],Integer.parseInt(bits[1]))));}c.setConnectTimeout(20000);c.setReadTimeout(90000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+p.getString("key",""));JSONObject body=new JSONObject();body.put("model",p.getString("model","gpt-5-mini"));body.put("input",history);body.put("store",false);try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String raw=read(in);if(code<200||code>=300)throw new Exception("HTTP "+code+": "+raw);JSONObject out=new JSONObject(raw);if(out.has("output_text"))return out.getString("output_text");JSONArray output=out.optJSONArray("output");if(output!=null)for(int i=0;i<output.length();i++){JSONArray content=output.getJSONObject(i).optJSONArray("content");if(content!=null)for(int j=0;j<content.length();j++){JSONObject z=content.getJSONObject(j);if(z.has("text"))return z.getString("text");}}return "鏈嶅姟宸插搷搴旓紝浣嗘湭杩斿洖鍙樉绀虹殑鏂囨湰銆?;}String read(InputStream in)throws IOException{if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);return s.toString();}}
}

